//POST
export const AGREGAR_ACTIVO = 'AGREGAR_ACTIVO'
export const AGREGAR_ACTIVO_EXITO = 'AGREGAR_ACTIVO_EXITO'
export const AGREGAR_ACTIVO_ERROR = 'AGREGAR_ACTIVO_ERROR'

//GET
export const COMENZAR_DESCARGA_ACTIVOS = 'COMENZAR_DESCARGA_ACTIVOS'
export const DESCARGA_ACTIVOS_EXITO = 'DESCARGA_ACTIVOS_EXITO'
export const DESCARGA_ACTIVOS_ERROR = 'DESCARGA_ACTIVOS_ERROR'

//EDIT
export const OBTENER_ACTIVO_EDITAR = 'OBTENER_ACTIVO_EDITAR'
export const COMENZAR_EDICION_ACTIVO = 'COMENZAR_EDICION_ACTIVO'
export const ACTIVO_EDITADO_EXITO = 'ACTIVO_EDITADO_EXITO'
export const ACTIVO_EDITADO_ERROR = 'ACTIVO_EDITADO_ERROR'

//DELETE
export const OBTENER_ACTIVO_ELIMINAR = 'OBTENER_ACTIVO_ELIMINAR'
export const ACTIVO_ELIMINADO_EXITO = 'ACTIVO_ELIMINADO_EXITO'
export const ACTIVO_ELIMINADO_ERROR = 'ACTIVO_ELIMINADO_ERROR'

//Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'