//POST
export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const AGREGAR_EMPLEADO_EXITO = 'AGREGAR_EMPLEADO_EXITO'
export const AGREGAR_EMPLEADO_ERROR = 'AGREGAR_EMPLEADO_ERROR'

//GET
export const COMENZAR_DESCARGA_EMPLEADOS = 'COMENZAR_DESCARGA_EMPLEADOS'
export const DESCARGA_EMPLEADOS_EXITO = 'DESCARGA_EMPLEADOS_EXITO'
export const DESCARGA_EMPLEADOS_ERROR = 'DESCARGA_EMPLEADOS_ERROR'

//EDIT
export const OBTENER_EMPLEADO_EDITAR = 'OBTENER_EMPLEADO_EDITAR'
export const COMENZAR_EDICION_EMPLEADO = 'COMENZAR_EDICION_EMPLEADO'
export const EMPLEADO_EDITADO_EXITO = 'EMPLEADO_EDITADO_EXITO'
export const EMPLEADO_EDITADO_ERROR = 'EMPLEADO_EDITADO_ERROR'

//DELETE
export const OBTENER_EMPLEADO_ELIMINAR = 'OBTENER_EMPLEADO_ELIMINAR'
export const EMPLEADO_ELIMINADO_EXITO = 'EMPLEADO_ELIMINADO_EXITO'
export const EMPLEADO_ELIMINADO_ERROR = 'EMPLEADO_ELIMINADO_ERROR'