export const AGREGAR_EMPLEADO = 'AGREGAR_EMPLEADO'
export const AGREGAR_EMPLEADO_EXITO = 'AGREGAR_EMPLEADO_EXITO'
export const AGREGAR_EMPLEADO_ERROR = 'AGREGAR_EMPLEADO_ERROR'

export const COMENZAR_DESCARGA_EMPLEADOS = 'COMENZAR_DESCARGA_EMPLEADOS'
export const DESCARGA_EMPLEADOS_EXITO = 'DESCARGA_EMPLEADOS_EXITO'
export const DESCARGA_EMPLEADOS_ERROR = 'DESCARGA_EMPLEADOS_ERROR'